import type { Redis } from "ioredis";
import { generateId, CHALLENGE_TTL_SECONDS, MAX_CHALLENGE_ATTEMPTS } from "@rekuway/security";
import type { ChallengeMetadata, ChallengePurpose } from "@rekuway/auth-core";

// The Rekuway Challenge Layer (spec section 16).
// Every challenge is: cryptographically random, short-lived, single-use,
// and invalidated after success or critical failure. This is the anchor
// that anti-replay (section 35) is built on.
//
// IMPORTANT: the actual random challenge VALUE is generated by
// @simplewebauthn/server (see lib/webauthn.ts), not by us — the library
// controls both generation and the base64url encoding sent to the browser,
// so we must store exactly what it returns rather than re-encoding our own
// random bytes. Passing our own pre-encoded string caused a double base64url
// encoding mismatch during verification.

function key(challengeId: string): string {
  return `challenge:${challengeId}`;
}

export class ChallengeStore {
  constructor(private readonly redis: Redis) {}

  async create(purpose: ChallengePurpose, userId: string | null, challenge: string): Promise<ChallengeMetadata> {
    const challengeId = generateId();
    const now = new Date();
    const ttl = purpose === "REGISTRATION" ? CHALLENGE_TTL_SECONDS.registration : CHALLENGE_TTL_SECONDS.login;
    const expiresAt = new Date(now.getTime() + ttl * 1000);

    const metadata: ChallengeMetadata = {
      challengeId,
      challenge,
      purpose,
      createdAt: now.toISOString(),
      expiresAt: expiresAt.toISOString(),
      status: "PENDING",
      attemptCount: 0,
      userId,
    };

    await this.redis.set(key(challengeId), JSON.stringify(metadata), "EX", ttl);
    return metadata;
  }

  async get(challengeId: string): Promise<ChallengeMetadata | null> {
    const raw = await this.redis.get(key(challengeId));
    if (!raw) return null;
    return JSON.parse(raw) as ChallengeMetadata;
  }

  async consume(challengeId: string, expectedPurpose: ChallengePurpose): Promise<ChallengeMetadata | null> {
    const metadata = await this.get(challengeId);
    if (!metadata) return null;
    if (metadata.purpose !== expectedPurpose) return null;
    if (metadata.status !== "PENDING") return null;
    if (new Date(metadata.expiresAt).getTime() < Date.now()) {
      await this.markExpired(challengeId);
      return null;
    }

    metadata.status = "USED";
    await this.redis.set(key(challengeId), JSON.stringify(metadata), "EX", 60);
    return metadata;
  }

  async recordFailedAttempt(challengeId: string): Promise<boolean> {
    const metadata = await this.get(challengeId);
    if (!metadata) return false;

    metadata.attemptCount += 1;
    if (metadata.attemptCount >= MAX_CHALLENGE_ATTEMPTS) {
      metadata.status = "BLOCKED";
    }

    const ttl = await this.redis.ttl(key(challengeId));
    await this.redis.set(key(challengeId), JSON.stringify(metadata), "EX", ttl > 0 ? ttl : 60);
    return metadata.status === "BLOCKED";
  }

  async markExpired(challengeId: string): Promise<void> {
    const metadata = await this.get(challengeId);
    if (!metadata) return;
    metadata.status = "EXPIRED";
    await this.redis.set(key(challengeId), JSON.stringify(metadata), "EX", 60);
  }

  async isReplay(challengeId: string): Promise<boolean> {
    const metadata = await this.get(challengeId);
    return metadata?.status === "USED";
  }
}